FROM python:3.8-buster

RUN apt-get update && apt-get install -y build-essential

RUN apt-get upgrade -y \
&& apt-get install -y \
&& apt-get -y install apt-utils gcc libpq-dev libsndfile-dev 
RUN pip install uwsgi
RUN apt-get install -y ffmpeg

WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app


CMD ["uwsgi", "--ini", "uwsgi.ini"]
