FROM python:3.8-buster

RUN apt-get update && apt-get install -y build-essential

RUN pip install uwsgi


WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app


CMD ["uwsgi", "--ini", "uwsgi.ini"]
