# Use the official AWS Lambda Python runtime as the base image
FROM public.ecr.aws/lambda/python:3.8

# Copy the Lambda function code and requirements.txt into the container
COPY requirements.txt ./

# Install any dependencies (if any)
RUN pip install -r requirements.txt

COPY . ./

# Set the Lambda handler
CMD ["lambda_function.lambda_handler"]
